/* Auto-generated by genmsg_cpp for file /home/kadir/workspace/work/Dropbox/metu-ros-pkg/trunk/affordance_learning/al_ext_utils/tabletop_object_detector/srv/ClearExclusionsList.srv */
#ifndef TABLETOP_OBJECT_DETECTOR_SERVICE_CLEAREXCLUSIONSLIST_H
#define TABLETOP_OBJECT_DETECTOR_SERVICE_CLEAREXCLUSIONSLIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace tabletop_object_detector
{
template <class ContainerAllocator>
struct ClearExclusionsListRequest_ {
  typedef ClearExclusionsListRequest_<ContainerAllocator> Type;

  ClearExclusionsListRequest_()
  {
  }

  ClearExclusionsListRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ClearExclusionsListRequest
typedef  ::tabletop_object_detector::ClearExclusionsListRequest_<std::allocator<void> > ClearExclusionsListRequest;

typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListRequest> ClearExclusionsListRequestPtr;
typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListRequest const> ClearExclusionsListRequestConstPtr;


template <class ContainerAllocator>
struct ClearExclusionsListResponse_ {
  typedef ClearExclusionsListResponse_<ContainerAllocator> Type;

  ClearExclusionsListResponse_()
  {
  }

  ClearExclusionsListResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ClearExclusionsListResponse
typedef  ::tabletop_object_detector::ClearExclusionsListResponse_<std::allocator<void> > ClearExclusionsListResponse;

typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListResponse> ClearExclusionsListResponsePtr;
typedef boost::shared_ptr< ::tabletop_object_detector::ClearExclusionsListResponse const> ClearExclusionsListResponseConstPtr;

struct ClearExclusionsList
{

typedef ClearExclusionsListRequest Request;
typedef ClearExclusionsListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ClearExclusionsList
} // namespace tabletop_object_detector

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tabletop_object_detector/ClearExclusionsListRequest";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tabletop_object_detector/ClearExclusionsListResponse";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
";
  }

  static const char* value(const  ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ClearExclusionsListRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ClearExclusionsListResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<tabletop_object_detector::ClearExclusionsList> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsList&) { return value(); } 
};

template<>
struct DataType<tabletop_object_detector::ClearExclusionsList> {
  static const char* value() 
  {
    return "tabletop_object_detector/ClearExclusionsList";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsList&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tabletop_object_detector/ClearExclusionsList";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsListRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tabletop_object_detector/ClearExclusionsList";
  }

  static const char* value(const tabletop_object_detector::ClearExclusionsListResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // TABLETOP_OBJECT_DETECTOR_SERVICE_CLEAREXCLUSIONSLIST_H

