/* Auto-generated by genmsg_cpp for file /home/kadir/workspace/work/Dropbox/metu-ros-pkg/trunk/affordance_learning/al_srvs/srv/GetCollisionObject.srv */
#ifndef AL_SRVS_SERVICE_GETCOLLISIONOBJECT_H
#define AL_SRVS_SERVICE_GETCOLLISIONOBJECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "arm_navigation_msgs/CollisionObject.h"

namespace al_srvs
{
template <class ContainerAllocator>
struct GetCollisionObjectRequest_ {
  typedef GetCollisionObjectRequest_<ContainerAllocator> Type;

  GetCollisionObjectRequest_()
  : id()
  , latest_scene_required(false)
  {
  }

  GetCollisionObjectRequest_(const ContainerAllocator& _alloc)
  : id(_alloc)
  , latest_scene_required(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  id;

  typedef uint8_t _latest_scene_required_type;
  uint8_t latest_scene_required;


  typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetCollisionObjectRequest
typedef  ::al_srvs::GetCollisionObjectRequest_<std::allocator<void> > GetCollisionObjectRequest;

typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectRequest> GetCollisionObjectRequestPtr;
typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectRequest const> GetCollisionObjectRequestConstPtr;


template <class ContainerAllocator>
struct GetCollisionObjectResponse_ {
  typedef GetCollisionObjectResponse_<ContainerAllocator> Type;

  GetCollisionObjectResponse_()
  : collision_object()
  {
  }

  GetCollisionObjectResponse_(const ContainerAllocator& _alloc)
  : collision_object(_alloc)
  {
  }

  typedef  ::arm_navigation_msgs::CollisionObject_<ContainerAllocator>  _collision_object_type;
   ::arm_navigation_msgs::CollisionObject_<ContainerAllocator>  collision_object;


  typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetCollisionObjectResponse
typedef  ::al_srvs::GetCollisionObjectResponse_<std::allocator<void> > GetCollisionObjectResponse;

typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectResponse> GetCollisionObjectResponsePtr;
typedef boost::shared_ptr< ::al_srvs::GetCollisionObjectResponse const> GetCollisionObjectResponseConstPtr;

struct GetCollisionObject
{

typedef GetCollisionObjectRequest Request;
typedef GetCollisionObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetCollisionObject
} // namespace al_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "196fefa8da3476552a728b12881ea731";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x196fefa8da347655ULL;
  static const uint64_t static_value2 = 0x2a728b12881ea731ULL;
};

template<class ContainerAllocator>
struct DataType< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "al_srvs/GetCollisionObjectRequest";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string id\n\
bool latest_scene_required\n\
\n\
";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "abb995c1732e96f8381e4304f36fec5d";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xabb995c1732e96f8ULL;
  static const uint64_t static_value2 = 0x381e4304f36fec5dULL;
};

template<class ContainerAllocator>
struct DataType< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "al_srvs/GetCollisionObjectResponse";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/CollisionObject collision_object\n\
\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/CollisionObject\n\
# a header, used for interpreting the poses\n\
Header header\n\
\n\
# the id of the object\n\
string id\n\
\n\
# The padding used for filtering points near the object.\n\
# This does not affect collision checking for the object.  \n\
# Set to negative to get zero padding.\n\
float32 padding\n\
\n\
#This contains what is to be done with the object\n\
CollisionObjectOperation operation\n\
\n\
#the shapes associated with the object\n\
arm_navigation_msgs/Shape[] shapes\n\
\n\
#the poses associated with the shapes - will be transformed using the header\n\
geometry_msgs/Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/CollisionObjectOperation\n\
#Puts the object into the environment\n\
#or updates the object if already added\n\
byte ADD=0\n\
\n\
#Removes the object from the environment entirely\n\
byte REMOVE=1\n\
\n\
#Only valid within the context of a CollisionAttachedObject message\n\
#Will be ignored if sent with an CollisionObject message\n\
#Takes an attached object, detaches from the attached link\n\
#But adds back in as regular object\n\
byte DETACH_AND_ADD_AS_OBJECT=2\n\
\n\
#Only valid within the context of a CollisionAttachedObject message\n\
#Will be ignored if sent with an CollisionObject message\n\
#Takes current object in the environment and removes it as\n\
#a regular object\n\
byte ATTACH_AND_REMOVE_AS_OBJECT=3\n\
\n\
# Byte code for operation\n\
byte operation\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/Shape\n\
byte SPHERE=0\n\
byte BOX=1\n\
byte CYLINDER=2\n\
byte MESH=3\n\
\n\
byte type\n\
\n\
\n\
#### define sphere, box, cylinder ####\n\
# the origin of each shape is considered at the shape's center\n\
\n\
# for sphere\n\
# radius := dimensions[0]\n\
\n\
# for cylinder\n\
# radius := dimensions[0]\n\
# length := dimensions[1]\n\
# the length is along the Z axis\n\
\n\
# for box\n\
# size_x := dimensions[0]\n\
# size_y := dimensions[1]\n\
# size_z := dimensions[2]\n\
float64[] dimensions\n\
\n\
\n\
#### define mesh ####\n\
\n\
# list of triangles; triangle k is defined by tre vertices located\n\
# at indices triangles[3k], triangles[3k+1], triangles[3k+2]\n\
int32[] triangles\n\
geometry_msgs/Point[] vertices\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::al_srvs::GetCollisionObjectRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.latest_scene_required);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetCollisionObjectRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::al_srvs::GetCollisionObjectResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.collision_object);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetCollisionObjectResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<al_srvs::GetCollisionObject> {
  static const char* value() 
  {
    return "767490c9fae8ddeb2332ce6d791ba7b2";
  }

  static const char* value(const al_srvs::GetCollisionObject&) { return value(); } 
};

template<>
struct DataType<al_srvs::GetCollisionObject> {
  static const char* value() 
  {
    return "al_srvs/GetCollisionObject";
  }

  static const char* value(const al_srvs::GetCollisionObject&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "767490c9fae8ddeb2332ce6d791ba7b2";
  }

  static const char* value(const al_srvs::GetCollisionObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<al_srvs::GetCollisionObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "al_srvs/GetCollisionObject";
  }

  static const char* value(const al_srvs::GetCollisionObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "767490c9fae8ddeb2332ce6d791ba7b2";
  }

  static const char* value(const al_srvs::GetCollisionObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<al_srvs::GetCollisionObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "al_srvs/GetCollisionObject";
  }

  static const char* value(const al_srvs::GetCollisionObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // AL_SRVS_SERVICE_GETCOLLISIONOBJECT_H

